#!/usr/bin/env bash
{ set +x; } 2>/dev/null
source_dir="$( cd -P "$( dirname "$0" )" >/dev/null 2>&1 && pwd )"
root_dir=$(cd $source_dir && cd ../.. && pwd)
cd $root_dir

if [ "$USE_DOTNET_WATCH" = "1" ]; then
    dotnet watch --project src/functions/Abbot.Functions.DotNet/Abbot.Functions.DotNet.csproj msbuild -t:Build,RunFunctions "src/functions/Abbot.Functions.DotNet/Abbot.Functions.DotNet.csproj" "$@"
else
    dotnet msbuild -t:Build,RunFunctions "src/functions/Abbot.Functions.DotNet/Abbot.Functions.DotNet.csproj" "$@"
fi
