#!/usr/bin/env bash
#/ Usage: script/generate-dts [-c|--check]
#/ Description: Generates TypeScript definitions for the Abbot.Web Internal JS API.
#/ Options:
#/   -c, --check - Run in check mode. Will return a non-zero exit code if the '.d.ts' files need to be regenerated.
{ set +x; } 2>/dev/null
source_dir="$( cd -P "$( dirname "$0" )" >/dev/null 2>&1 && pwd )"
root_dir=$(cd $source_dir && cd ../ && pwd)
cd $root_dir
source script/helpers/_utils.sh

check=false

while (( "$#" )); do
    key="$1"
    shift
    case "$key" in
        -c|--check)
            check=true
            ;;
        -\?|-h|--help)
            grep '^#/' <"$0" | cut -c4-
            exit
        ;;
    esac
done

swagger_url=https://localhost:4979/swagger/internal/swagger.json

cd "$root_dir/src/product/Abbot.Web"
tmp_file=$(mktemp)

if ! curl --insecure -o $tmp_file $swagger_url; then
    echo "Failed to download swagger.json from $swagger_url"
    echo "Is Abbot.Web running?"
    exit 1
fi
npx openapi-typescript-codegen -o "$root_dir/src/product/Abbot.Web/assets/ts/api/internal" -i $tmp_file --exportCore false --exportServices false --useUnionTypes
rm $tmp_file

if $check; then
    echo "Checking if any files are changed..."
    if git diff --quiet HEAD -- "$root_dir/src/product/Abbot.Web/assets/ts/api"; then
        echo "No changes detected."
        exit 0
    else
        echo "You changed the API structure! Run 'script/generate-dts' to regenerate the TypeScript typings."
        exit 1
    fi
fi
