#!/usr/bin/env bash
#/ Usage: script/runner
#/ Description: Launches the .NET Skill Runner
{ set +x; } 2>/dev/null
source_dir="$( cd -P "$( dirname "$0" )" >/dev/null 2>&1 && pwd )"
root_dir=$(cd $source_dir && cd ../ && pwd)
cd $root_dir
source script/helpers/_utils.sh

while (( "$#" )); do
  key="$1"
  shift
  case "$key" in
    -\?|-h|--help)
      grep '^#/' <"$0" | cut -c4-
      exit
    ;;
  esac
done

if type overmind >/dev/null 2>&1; then
  overmind start --procfile "$root_dir/Procfile" --processes dotnet-runner
elif type hivemind >/dev/null 2>&1; then
  hivemind --processes dotnet-runner "$root_dir/Procfile"
else
  dotnet watch --project src/functions/Abbot.Functions.DotNet/Abbot.Functions.DotNet.csproj msbuild -t:Build,RunFunctions
fi
