#!/usr/bin/env bash
#/ Usage: script/start-services
#/ Description: Launches background services required by Abbot development, using docker-compose.
{ set +x; } 2>/dev/null
source_dir="$( cd -P "$( dirname "$0" )" >/dev/null 2>&1 && pwd )"
root_dir=$(cd $source_dir && cd ../ && pwd)
cd $root_dir
source script/helpers/_utils.sh

if ! type docker-compose >/dev/null 2>&1; then
  fatal "docker-compose is required to run this script. Please install it and try again."
fi

# Shut down old services
docker stop abbot_postgres >/dev/null 2>&1 || true
docker rm abbot_postgres >/dev/null 2>&1 || true
docker stop abbot_ngrok >/dev/null 2>&1 || true
docker rm abbot_ngrok >/dev/null 2>&1 || true

docker-compose up -d