#!/usr/bin/env bash
#/ Usage: script/watch-js [<configuration>]
#/ Description: Launches the JS builds in 'watch' mode (reloading it on any changes)
{ set +x; } 2>/dev/null
source_dir="$( cd -P "$( dirname "$0" )" >/dev/null 2>&1 && pwd )"
root_dir=$(cd $source_dir && cd ../ && pwd)
cd $root_dir
source script/helpers/_utils.sh

configuration=
while (( "$#" )); do
  key="$1"
  shift
  case "$key" in
    -\?|-h|--help)
      grep '^#/' <"$0" | cut -c4-
      exit
    ;;
    *)
      if [ -z $configuration ]; then
        configuration=$key
      fi
    ;;
  esac
done

if [ -z $configuration ]; then
  configuration=Debug
fi

if type overmind >/dev/null 2>&1; then
  overmind start --procfile "$root_dir/Procfile" --processes abbot-web-js,serious-razor-js
elif type hivemind >/dev/null 2>&1; then
  hivemind --processes abbot-web-js,serious-razor-js "$root_dir/Procfile"
else
  echo "Install overmind or hivemind for snazzy process management."
  script/procs/js-build src/product/Abbot.Web &
  script/procs/js-build src/product/Serious.Razor &
fi

# Wait for both jobs to terminate.
wait