name: 'Delete old artifacts'
on:
  schedule:
    - cron: '17 2 * * *' # Runs nightly at 2:17am UTC

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 7 # Setting this to 0 will delete all artifacts
