name: Mark PRs as Stale after 14 days

on:
  schedule:
    # Run every day at midnight UTC
    - cron: '0 0 * * *'

permissions:
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          stale-pr-message: "Hey, this PR has been open for a while. Someone should look at it, or we can just close it if it's no longer relevant"
          stale-pr-label: "stale"
          days-before-pr-stale: 14

          # Don't mark issues as stale.
          days-before-issue-stale: -1

          # Don't close stale issues/prs
          days-before-close: -1